# Generated by Django 5.1.4 on 2024-12-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_downvotes_post_upvotes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voters',
            field=models.JSONField(default=dict),
        ),
    ]
