# Generated by Django 4.2.11 on 2025-01-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voters',
            field=models.JSONField(default=dict),
        ),
    ]
